### ISSUE TITLE
How to integrate with 3rd party service

### ISSUE THREAD

**Issue by engelmi** [eclipse-bluechi/.eclipsefdn#14]
Hi everyone, 
we would like to integrate with the 3rd party service [coveralls.io](https://coveralls.io) in order to track the code coverage from our tests (see issue https://github.com/eclipse-bluechi/bluechi/issues/694). Since this service requires access to the organization/repository, we would need to enable this. 
How can we achieve that?
Thanks!

**Comment by pstankie** [comment]
@engelmi Please created EF Helpdesk issue at https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues

**Comment by engelmi** [comment]
Done :heavy_check_mark: 
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4261

Closing.
