### ISSUE TITLE
Can't merge to bluechi-ppa

### ISSUE THREAD

**Issue by engelmi** [eclipse-bluechi/.eclipsefdn#19]
In the new [bluechi-ppa](https://github.com/eclipse-bluechi/bluechi-ppa) repository the approval of an [automotive-bluechi-committers](https://github.com/orgs/eclipse-bluechi/teams/automotive-bluechi-committers) doesn't seem to be enough to get PRs merged. 
See for example:
https://github.com/eclipse-bluechi/bluechi-ppa/pull/1

@netomi Maybe I configured the bluechi-ppa repository wrong? Should I create a gitlab ticket?

**Comment by netomi** [comment]
permissions have not been setup yet. So once a repo is created you will need to wait 2-3h for the sync script to run to setup the permissions. So currently noone can write to the repo so the review is not complete (as it requires a approval from someone with write permissions on the repo).

**Comment by netomi** [comment]
I gave committers write permissions manually, and you can merge now.

**Comment by engelmi** [comment]
Ah, didn't know about this. 
Thanks for your help!
