### ISSUE TITLE
How to add secrets

### ISSUE THREAD

**Issue by engelmi** [eclipse-bluechi/.eclipsefdn#2]
Hi everyone, 
I'd like to add a new repository secret to the [BlueChi repo](https://github.com/eclipse-bluechi/bluechi) and I am wondering how to properly pass the value in the .jsonnet configuration, e.g. for the [pypi token](https://github.com/eclipse-bluechi/.eclipsefdn/blob/main/otterdog/eclipse-bluechi.jsonnet#L86-L88). 
Thanks!

**Comment by netomi** [comment]
for the secret values, you should send them via a secure channel to EF IT staff. We add the secret then in our internal credential store and reference it in the configuration. You could already create a PR to address that topic with the desired secret name, and we fill in then the value from the credential store.

**Comment by engelmi** [comment]
Thanks! @netomi 
I created #3 to add the secret name as suggested. What secure channels are used by the EF IT staff that I can use to send them the secret?

**Comment by netomi** [comment]
@pstankie @heurtematte  can you chime in here as you usually receive secrets from project?

**Comment by engelmi** [comment]
@netomi @pstankie @heurtematte Or is it be possible to grant permissions for editing secrets to the [project leads](https://github.com/orgs/eclipse-bluechi/teams/automotive-bluechi-project-leads) on all repositories? We can still add the secrets names in the config here, of course. But then we can quickly add/update them, e.g. when they expire, otherwise we are blocked.

**Comment by engelmi** [comment]
Any updates on this?

**Comment by netomi** [comment]
Editing secrets in a repository or organization requires to have administrator access so thats why we came up with a solution like that to ease the process. From my experience with other projects that works quite straight-forward and quick. We need to overcome the initial hurdle on how to send secret values via a secure channel.

With some projects we share a slack channel where we exchange secrets, maybe matrix would be a good option as it supports e2e encryption as well wdyt @heurtematte ?

**Comment by engelmi** [comment]
Makes sense @netomi 
Maybe a GH issue is the wrong channel to discuss this? Should I open an issue in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues?

**Comment by netomi** [comment]
yes please, I guess the other people miss notifications on this ticket as they are busy doing other work. I am used to watch my GitHub notifications, but I know that it can easily be missed, especially if you are member of many organizations as we are as EF IT staff.
